<a href="https://colab.research.google.com/github/theabktech/Credit-Card-Fraud-Detection/blob/main/Credit_Card_Fraud_Model_Exploration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

In [3]:
!pip install requests
!pip install tabulate
!pip install "colorama>=0.3.8"
!pip install future

Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (2.23.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests) (2021.5.30)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests) (1.24.3)
Requirement already satisfied: tabulate in /usr/local/lib/python3.7/dist-packages (0.8.9)
Collecting colorama>=0.3.8
  Downloading https://files.pythonhosted.org/packages/44/98/5b86278fbbf250d239ae0ecb724f8572af1c91f4a11edf4d36a206189440/colorama-0.4.4-py2.py3-none-any.whl
Installing collected packages: colorama
Successfully installed colorama-0.4.4
Requirement already satisfied: future in /usr/local/lib/python3.7/dist-packages (0.16.0)

In [4]:
!pip install -f http://h2o-release.s3.amazonaws.com/h2o/latest_stable_Py.html h2o

Looking in links: http://h2o-release.s3.amazonaws.com/h2o/latest_stable_Py.html
WARNING: The repository located at h2o-release.s3.amazonaws.com is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host h2o-release.s3.amazonaws.com'.
Collecting h2o
  Downloading https://files.pythonhosted.org/packages/8c/6a/0ee4e2387e31cb472a952a44cffd72f1b471c51f28f0ceeeaa5e4709be1b/h2o-3.32.1.4.tar.gz (164.8MB)
     |████████████████████████████████| 164.8MB 36kB/s
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from h2o) (2.23.0)
Requirement already satisfied: tabulate in /usr/local/lib/python3.7/dist-packages (from h2o) (0.8.9)
Requirement already satisfied: future in /usr/local/lib/python3.7/dist-packages (from h2o) (0.16.0)
Requirement already satisfied: colorama>=0.3.8 in /usr/local/lib/python3.7/dist-packages (from h2o) (0.4.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->h2o) (2021.5.30)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->h2o) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->h2o) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->h2o) (1.24.3)
Building wheels for collected packages: h2o
  Building wheel for h2o (setup.py) ... done
  Created wheel for h2o: filename=h2o-3.32.1.4-py2.py3-none-any.whl size=164871668 sha256=8befa81a729071063027ba9bb6661b4e86155bc77ca2d33c6cfcb8833a7d4005
  Stored in directory: /root/.cache/pip/wheels/67/76/54/89d7711536d5bb0d010bf35a34deca3eddc757efba78dbc74f
Successfully built h2o
Installing collected packages: h2o
Successfully installed h2o-3.32.1.4

In [6]:
dataset = pd.read_csv("/content/drive/MyDrive/Credit Card Fraud Dataset/creditcard.csv")

In [8]:
test = dataset.sample(frac=0.1)
train = dataset.drop(test.index)

test.to_csv("/content/drive/MyDrive/Credit Card Fraud Dataset/test.csv")
train.to_csv("/content/drive/MyDrive/Credit Card Fraud Dataset/train.csv")

In [9]:
import h2o
from h2o.automl import H2OAutoML

h2o.init()

# Import a sample binary outcome train/test set into H2O
train = h2o.import_file("/content/drive/MyDrive/Credit Card Fraud Dataset/train.csv")
test = h2o.import_file("/content/drive/MyDrive/Credit Card Fraud Dataset/test.csv")

# Identify predictors and response
x = train.columns
y = "Class"
x.remove(y)

# For binary classification, response should be a factor
train[y] = train[y].asfactor()
test[y] = test[y].asfactor()

# Run AutoML for 20 base models (limited to 1 hour max runtime by default)
aml = H2OAutoML(max_models=25, seed=1)
aml.train(x=x, y=y, training_frame=train)

# View the AutoML Leaderboard
lb = aml.leaderboard
lb.head(rows=lb.nrows)

Checking whether there is an H2O instance running at http://localhost:54321 ..... not found.
Attempting to start a local H2O server...
  Java Version: openjdk version "11.0.11" 2021-04-20; OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.18.04); OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.18.04, mixed mode, sharing)
  Starting server from /usr/local/lib/python3.7/dist-packages/h2o/backend/bin/h2o.jar
  Ice root: /tmp/tmpne46xt0s
  JVM stdout: /tmp/tmpne46xt0s/h2o_unknownUser_started_from_python.out
  JVM stderr: /tmp/tmpne46xt0s/h2o_unknownUser_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321 ... successful.

--------------------------  ------------------------------------------------------------------
H2O_cluster_uptime:         05 secs
H2O_cluster_timezone:       Etc/UTC
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.32.1.4
H2O_cluster_version_age:    7 days, 20 hours and 19 minutes
H2O_cluster_name:           H2O_from_python_unknownUser_z36jyj
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    3.174 Gb
H2O_cluster_total_cores:    2
H2O_cluster_allowed_cores:  2
H2O_cluster_status:         accepting new members, healthy
H2O_connection_url:         http://127.0.0.1:54321
H2O_connection_proxy:       {"http": null, "https": null}
H2O_internal_security:      False
H2O_API_Extensions:         Amazon S3, XGBoost, Algos, AutoML, Core V3, TargetEncoder, Core V4
Python_version:             3.7.10 final
--------------------------  ------------------------------------------------------------------

Parse progress: |█████████████████████████████████████████████████████████| 100%
Parse progress: |█████████████████████████████████████████████████████████| 100%
AutoML progress: |████████████████████████████████████████████████████████| 100%

model_id,auc,logloss,aucpr,mean_per_class_error,rmse,mse
XGBoost_grid__1_AutoML_20210716_105821_model_1,0.980766,0.00255923,0.849497,0.0929446,0.0202041,0.000408206
StackedEnsemble_BestOfFamily_AutoML_20210716_105821,0.980368,0.00250673,0.852104,0.0895277,0.0200114,0.000400456
XGBoost_2_AutoML_20210716_105821,0.979486,0.00262783,0.844354,0.0998273,0.0205607,0.000422742
XGBoost_grid__1_AutoML_20210716_105821_model_6,0.979384,0.00268215,0.844232,0.0998332,0.020609,0.000424731
XGBoost_grid__1_AutoML_20210716_105821_model_5,0.979086,0.00264516,0.843077,0.0952597,0.0206398,0.000426002
StackedEnsemble_AllModels_AutoML_20210716_105821,0.97826,0.00251054,0.854608,0.104399,0.0199342,0.000397372
XGBoost_grid__1_AutoML_20210716_105821_model_3,0.977174,0.00263405,0.844111,0.0975357,0.0204485,0.000418139
XGBoost_grid__1_AutoML_20210716_105821_model_2,0.97593,0.00290988,0.842847,0.103266,0.0206768,0.000427532
XGBoost_3_AutoML_20210716_105821,0.975382,0.00261961,0.854237,0.107829,0.0199684,0.000398736
XGBoost_1_AutoML_20210716_105821,0.974471,0.00266593,0.846565,0.0998273,0.0204247,0.000417166
GLM_1_AutoML_20210716_105821,0.972556,0.0040938,0.733792,0.115988,0.0261847,0.000685637
XGBoost_grid__1_AutoML_20210716_105821_model_4,0.970543,0.00288628,0.846872,0.0952421,0.0201497,0.00040601
DeepLearning_grid__2_AutoML_20210716_105821_model_1,0.961766,0.00453169,0.752867,0.104487,0.0245335,0.000601892
DRF_1_AutoML_20210716_105821,0.955286,0.00370189,0.839376,0.100962,0.0205736,0.000423271
XRT_1_AutoML_20210716_105821,0.951084,0.00428048,0.83663,0.105544,0.0205855,0.000423763
DeepLearning_1_AutoML_20210716_105821,0.945675,0.00726677,0.716454,0.11251,0.0254515,0.000647777
DeepLearning_grid__1_AutoML_20210716_105821_model_1,0.945302,0.00843128,0.731602,0.103342,0.0243091,0.000590933
DeepLearning_grid__3_AutoML_20210716_105821_model_1,0.934096,0.00661178,0.70561,0.102195,0.0245976,0.000605044
GBM_grid__1_AutoML_20210716_105821_model_4,0.922873,0.0219996,0.559034,0.122978,0.032498,0.00105612
GBM_grid__1_AutoML_20210716_105821_model_1,0.8184,0.0219488,0.563268,0.148112,0.0319673,0.00102191
GBM_grid__1_AutoML_20210716_105821_model_3,0.800768,0.0196358,0.551209,0.154996,0.0297047,0.00088237
GBM_1_AutoML_20210716_105821,0.795809,0.0187501,0.548161,0.183625,0.0299643,0.000897858
GBM_2_AutoML_20210716_105821,0.790748,0.0230102,0.539583,0.169887,0.0309689,0.000959075
GBM_grid__1_AutoML_20210716_105821_model_2,0.777698,0.0204098,0.49026,0.203181,0.0324956,0.00105596
GBM_4_AutoML_20210716_105821,0.768868,0.0246549,0.518506,0.16876,0.0316957,0.00100461
GBM_3_AutoML_20210716_105821,0.758451,0.0225702,0.532198,0.176764,0.0305663,0.000934296
GBM_5_AutoML_20210716_105821,0.756049,0.0244011,0.495569,0.212299,0.0341196,0.00116415

In [10]:
aml.leader

Model Details
=============
H2OXGBoostEstimator :  XGBoost
Model Key:  XGBoost_grid__1_AutoML_20210716_105821_model_1


Model Summary:

     number_of_trees
0              102.0

ModelMetricsBinomial: xgboost
** Reported on train data. **

MSE: 0.00023397603181985195
RMSE: 0.015296275096239998
LogLoss: 0.0011880031609430713
Mean Per-Class Error: 0.011576299090671482
AUC: 0.9993167935907094
AUCPR: 0.9479398240793175
Gini: 0.9986335871814187

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.3663409352302551:

                 0      1   Error              Rate
0      0  255880.0   10.0     0.0   (10.0/255890.0)
1      1      55.0  381.0  0.1261      (55.0/436.0)
2  Total  255935.0  391.0  0.0003   (65.0/256326.0)

Maximum Metrics: Maximum metrics at their respective thresholds

                         metric  threshold          value    idx
0                        max f1   0.366341       0.921403  137.0
1                        max f2   0.131945       0.909508  168.0
2                  max f0point5   0.546806       0.960334  120.0
3                  max accuracy   0.378013       0.999746  135.0
4                 max precision   0.999631       1.000000    0.0
5                    max recall   0.000384       1.000000  375.0
6               max specificity   0.999631       1.000000    0.0
7              max absolute_mcc   0.366341       0.922647  137.0
8    max min_per_class_accuracy   0.003052       0.988315  330.0
9   max mean_per_class_accuracy   0.003052       0.988424  330.0
10                      max tns   0.999631  255890.000000    0.0
11                      max fns   0.999631     430.000000    0.0
12                      max fps   0.000004  255890.000000  399.0
13                      max tps   0.000384     436.000000  375.0
14                      max tnr   0.999631       1.000000    0.0
15                      max fnr   0.999631       0.986239    0.0
16                      max fpr   0.000004       1.000000  399.0
17                      max tpr   0.000384       1.000000  375.0

Gains/Lift Table: Avg response rate:  0.17 %, avg score:  0.17 %

    group  cumulative_data_fraction  ...  cumulative_gain  kolmogorov_smirnov
0       1                  0.010003  ...      9713.680602            0.973304
1       2                  0.020002  ...      4853.664625            0.972478
2       3                  0.030001  ...      3210.302848            0.964759
3       4                  0.040004  ...      2388.299129            0.957037
4       5                  0.050003  ...      1895.303865            0.949318
5       6                  0.100002  ...       899.984395            0.901532
6       7                  0.150000  ...       566.664933            0.851448
7       8                  0.200003  ...       399.992198            0.801360
8       9                  0.300001  ...       233.332466            0.701192
9      10                  0.400006  ...       149.996099            0.601016
10     11                  0.500000  ...       100.000000            0.500852
11     12                  0.600002  ...        66.666233            0.400680
12     13                  0.699999  ...        42.857302            0.300512
13     14                  0.800001  ...        24.999878            0.200340
14     15                  0.899998  ...        11.111304            0.100172
15     16                  1.000000  ...         0.000000            0.000000

[16 rows x 14 columns]

ModelMetricsBinomial: xgboost
** Reported on cross-validation data. **

MSE: 0.00040820609637637085
RMSE: 0.020204110878144846
LogLoss: 0.00255922743641938
Mean Per-Class Error: 0.05629829115936791
AUC: 0.9807657058419239
AUCPR: 0.8494968994299033
Gini: 0.9615314116838478

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.3169921636581421:

                 0      1   Error               Rate
0      0  255862.0   28.0  0.0001    (28.0/255890.0)
1      1      81.0  355.0  0.1858       (81.0/436.0)
2  Total  255943.0  383.0  0.0004   (109.0/256326.0)

Maximum Metrics: Maximum metrics at their respective thresholds

                         metric  threshold          value    idx
0                        max f1   0.316992       0.866911  152.0
1                        max f2   0.289925       0.835289  156.0
2                  max f0point5   0.756978       0.906040  110.0
3                  max accuracy   0.316992       0.999575  152.0
4                 max precision   0.999575       1.000000    0.0
5                    max recall   0.000009       1.000000  398.0
6               max specificity   0.999575       1.000000    0.0
7              max absolute_mcc   0.316992       0.868525  152.0
8    max min_per_class_accuracy   0.000604       0.931193  368.0
9   max mean_per_class_accuracy   0.001534       0.943702  350.0
10                      max tns   0.999575  255890.000000    0.0
11                      max fns   0.999575     429.000000    0.0
12                      max fps   0.000004  255890.000000  399.0
13                      max tps   0.000009     436.000000  398.0
14                      max tnr   0.999575       1.000000    0.0
15                      max fnr   0.999575       0.983945    0.0
16                      max fpr   0.000004       1.000000  399.0
17                      max tpr   0.000009       1.000000  398.0

Gains/Lift Table: Avg response rate:  0.17 %, avg score:  0.16 %

    group  cumulative_data_fraction  ...  cumulative_gain  kolmogorov_smirnov
0       1                  0.010003  ...      8773.585031            0.879107
1       2                  0.020002  ...      4417.925607            0.885173
2       3                  0.030001  ...      2942.726405            0.884347
3       4                  0.040004  ...      2193.363252            0.878922
4       5                  0.050003  ...      1748.522891            0.875799
5       6                  0.100002  ...       842.645840            0.844095
6       7                  0.150000  ...       545.258261            0.819283
7       8                  0.200003  ...       385.084173            0.771493
8       9                  0.300001  ...       226.451750            0.680515
9      10                  0.400002  ...       146.558190            0.587235
10     11                  0.500000  ...        97.706422            0.489364
11     12                  0.600002  ...        65.901709            0.396085
12     13                  0.700124  ...        42.176637            0.295792
13     14                  0.800001  ...        24.426484            0.195745
14     15                  0.899998  ...        11.111304            0.100172
15     16                  1.000000  ...         0.000000            0.000000

[16 rows x 14 columns]

Cross-Validation Metrics Summary:

                                     mean  ...    cv_4_valid    cv_5_valid
0                  accuracy     0.9995826  ...     0.9996099    0.99957085
1                       auc     0.9813028  ...    0.98363155     0.9803143
2                       err   4.174373E-4  ...  3.9012972E-4   4.291427E-4
3                 err_count          21.4  ...          20.0          22.0
4                  f0point5      0.903906  ...     0.8662614    0.90529245
5                        f1      0.866085  ...     0.8507463     0.8552632
6                        f2     0.8321578  ...     0.8357771     0.8104738
7            lift_top_group      88.66143  ...      92.69034      81.87182
8                   logloss  0.0025592272  ...  0.0020329899   0.002778001
9       max_per_class_error    0.18862595  ...    0.17391305    0.21686748
10                      mcc     0.8686025  ...    0.85093135      0.858711
11  mean_per_class_accuracy    0.90563816  ...    0.91296536     0.8915272
12     mean_per_class_error    0.09436182  ...    0.08703465    0.10847281
13                      mse  4.0820608E-4  ...   3.701038E-4  4.0475785E-4
14                   pr_auc     0.8470252  ...     0.8454299     0.8128081
15                precision     0.9316975  ...     0.8769231      0.942029
16                       r2    0.75591844  ...      0.724653    0.74959564
17                   recall    0.81137407  ...    0.82608694    0.78313255
18                     rmse   0.020124832  ...   0.019238083   0.020118594
19              specificity     0.9999023  ...     0.9998437    0.99992186

[20 rows x 8 columns]

Scoring History:

                timestamp  ... training_lift  training_classification_error
0     2021-07-16 11:43:24  ...      1.000000                       0.998299
1     2021-07-16 11:43:27  ...      1.000000                       0.000589
2     2021-07-16 11:43:29  ...      1.000000                       0.000468
3     2021-07-16 11:43:31  ...     85.017140                       0.000421
4     2021-07-16 11:43:33  ...     86.509019                       0.000402
5     2021-07-16 11:43:36  ...     90.570183                       0.000390
6     2021-07-16 11:43:38  ...     91.258058                       0.000375
7     2021-07-16 11:43:40  ...     91.945933                       0.000343
8     2021-07-16 11:43:43  ...     94.009557                       0.000347
9     2021-07-16 11:43:45  ...     93.452235                       0.000339
10    2021-07-16 11:43:47  ...     94.697432                       0.000328
11    2021-07-16 11:43:50  ...     95.156015                       0.000324
12    2021-07-16 11:43:52  ...     95.843890                       0.000312
13    2021-07-16 11:43:55  ...     96.302473                       0.000304
14    2021-07-16 11:43:57  ...     96.302473                       0.000300
15    2021-07-16 11:44:00  ...     96.531765                       0.000300
16    2021-07-16 11:44:02  ...     96.761056                       0.000293
17    2021-07-16 11:44:05  ...     97.219640                       0.000277
18    2021-07-16 11:44:08  ...     97.448931                       0.000269
19    2021-07-16 11:44:11  ...     98.136806                       0.000257

[20 rows x 10 columns]

See the whole table with table.as_data_frame()

Variable Importances:

   variable  relative_importance  scaled_importance  percentage
0       V14          1124.420166           1.000000    0.242666
1       V17           746.738220           0.664110    0.161157
2       V10           638.948853           0.568247    0.137894
3       V12           271.110168           0.241111    0.058509
4        V4           242.140350           0.215347    0.052257
5       V11           140.859390           0.125273    0.030399
6        V7           127.454514           0.113351    0.027507
7       V16           108.138649           0.096173    0.023338
8        V8           103.526848           0.092071    0.022343
9       V26           101.709427           0.090455    0.021950
10      V28            70.980316           0.063126    0.015319
11   Amount            68.884758           0.061262    0.014866
12      V20            67.716461           0.060223    0.014614
13      V19            66.089989           0.058777    0.014263
14       C1            58.931198           0.052410    0.012718
15      V27            58.334469           0.051880    0.012589
16       V3            56.056458           0.049854    0.012098
17       V2            52.158360           0.046387    0.011257
18      V15            50.573429           0.044977    0.010914
19      V18            50.111145           0.044566    0.010815

See the whole table with table.as_data_frame()

In [11]:
lb = h2o.automl.get_leaderboard(aml, extra_columns = 'ALL')
lb

model_id,auc,logloss,aucpr,mean_per_class_error,rmse,mse,training_time_ms,predict_time_per_row_ms,algo
XGBoost_grid__1_AutoML_20210716_105821_model_1,0.980766,0.00255923,0.849497,0.0929446,0.0202041,0.000408206,52253,0.004852,XGBoost
StackedEnsemble_BestOfFamily_AutoML_20210716_105821,0.980368,0.00250673,0.852104,0.0895277,0.0200114,0.000400456,21061,0.037323,StackedEnsemble
XGBoost_2_AutoML_20210716_105821,0.979486,0.00262783,0.844354,0.0998273,0.0205607,0.000422742,40037,0.003344,XGBoost
XGBoost_grid__1_AutoML_20210716_105821_model_6,0.979384,0.00268215,0.844232,0.0998332,0.020609,0.000424731,47676,0.003223,XGBoost
XGBoost_grid__1_AutoML_20210716_105821_model_5,0.979086,0.00264516,0.843077,0.0952597,0.0206398,0.000426002,68333,0.004301,XGBoost
StackedEnsemble_AllModels_AutoML_20210716_105821,0.97826,0.00251054,0.854608,0.104399,0.0199342,0.000397372,45834,0.075135,StackedEnsemble
XGBoost_grid__1_AutoML_20210716_105821_model_3,0.977174,0.00263405,0.844111,0.0975357,0.0204485,0.000418139,72575,0.004251,XGBoost
XGBoost_grid__1_AutoML_20210716_105821_model_2,0.97593,0.00290988,0.842847,0.103266,0.0206768,0.000427532,45630,0.003182,XGBoost
XGBoost_3_AutoML_20210716_105821,0.975382,0.00261961,0.854237,0.107829,0.0199684,0.000398736,44494,0.004604,XGBoost
XGBoost_1_AutoML_20210716_105821,0.974471,0.00266593,0.846565,0.0998273,0.0204247,0.000417166,43449,0.003478,XGBoost